### ISSUE TITLE
new data record with old validation results

### ISSUE THREAD

**Issue by wizardfan** [cnr-ibba/IMAGE-InjectTool#87] opened 2020-01-20 14:28 UTC
**Describe the bug**
Records with unexpected validation status

**To Reproduce**
Create a new submission with the example cryoweb file (3 animals 1 sample)
Do the validation
Reload the data source file with the same example cryoweb file
Edit the data

**Expected behavior**
All records without validation result (newly loaded data has not been validated)

**Comment by bunop** [comment] 2020-01-20 14:34
mmh, well yes. But your submission will be in *loaded* state and need to be validated before doing anything, is it correct? I agree that the old validation status need to be described as *unknown* (or removed). When you re-do the validation, all this stuff will fixed and consistent with the new data

**Comment by wizardfan** [comment] 2020-01-20 14:35
Though it prompts "Warning! by reloading data you will replace existing data. Old data not described in the new file will remain unchanged"
the records are NOT overwritten as the change I made to the record is still there.

**Comment by bunop** [comment] 2020-01-20 14:41
@wizardfan please help me to make this reproducibile: please specify the mofications you made and what you did. This could be more serious than the old validation status

**Comment by wizardfan** [comment] 2020-01-20 15:33
Steps to reproduce the behavior:
Create a new submission with the example cryoweb file (3 animals 1 sample)
Do the validation which shows that one animal fails the validation
Fix it => input any Birth location value
Save the record => all pass
Reload the data source file with the same example cryoweb file
Do the validation => all pass this time

**Comment by bunop** [comment] 2020-01-20 15:52
What is the example cryoweb file? https://github.com/cnr-ibba/IMAGE-InjectTool/blob/master/django-data/image/common/tests/cryoweb_test_data_only.sql ?

**Comment by wizardfan** [comment] 2020-01-20 15:58
yes, that is the one

**Comment by bunop** [comment] 2020-01-20 16:03
If I've understand the problem,  the `Birth location` attribute isn't modelled in cryoweb database (so no cryoweb import could pass the validation stage after import). This means that I couldn't overwrite this value during the import, and the validation is still ok since this column isn't overwritten. I wonder if I need to unset this value, but this means that you need to fix this column for every sample every time you reload a dataset. Consider having a cryoweb with thousands of samples. After fix the validation, you will have to fix this column again if you reload your dataset. I think that in such case, is correct to keep this column as it is when overwriting data. Do you agree? did you see the same for other columns?

**Comment by wizardfan** [comment] 2020-01-20 16:12
Alexey provides the function to do the batch update which should solve this problem.
The error is birth location is empty but the location accuracy is 'unknown accuracy level' rather than 'missing information', the validation tool detects it correctly. 
The example file maybe deliberately get changed to trigger this error, otherwise as you said, no birth location from CryoWeb dump, neither will the accuracy level which should have the default value as 'missing geographic information'
My opinion is still if you claim to overwrite the record, everything needs to be overwritten, otherwise may cause some hard-to-find bugs in future.

**Comment by bunop** [comment] 2020-02-26 17:47
At the moment this seems not to be a bug: user replace the data that currently have in their datasource. If datasource lacks of some column I can't set other columns as `NULL` easily. For instance, *cryoweb* lacks a lot of column described in *UID* and user plan to add infos not included in cryoweb: by resetting these columns all those operation will be lost. A similar consideration could be done for *CRBanim*. Using batch update is not a solution since it could fix only validation errors and is limited only to some modifications, as described in #49. This issue will be closed for the moment

**Closed as completed by bunop** 2020-02-26 17:47 UTC
Labels: enhancement, wontfix
